# Generated by Django 4.2.30 on 2026-06-27 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Manşet')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='Kampanya Metni')),
                ('badge_text', models.CharField(blank=True, help_text='Örn: Hafta sonu fırsatı, Yeni sezon, %20 indirim', max_length=60, verbose_name='Etiket')),
                ('image', models.ImageField(blank=True, null=True, upload_to='campaigns/', verbose_name='Kampanya Görseli')),
                ('link_text', models.CharField(blank=True, default='İncele', max_length=60, verbose_name='Buton Metni')),
                ('link_url', models.CharField(blank=True, help_text='Site içi veya dış bağlantı. Boş bırakılırsa ana sayfaya gider.', max_length=300, verbose_name='Bağlantı')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ana Sayfa Reklam Panosu',
                'verbose_name_plural': 'Ana Sayfa Reklam Panoları',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_override', models.CharField(blank=True, help_text='Boş bırakılırsa ürün adı kullanılır.', max_length=180, verbose_name='Vitrin Başlığı')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_slots', to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Vitrin Ürünü',
                'verbose_name_plural': 'Ana Sayfa Vitrin Ürünleri',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeaturedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_override', models.CharField(blank=True, help_text='Boş bırakılırsa kategori adı kullanılır.', max_length=100, verbose_name='Görünen Ad')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_slots', to='store.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Ana Sayfa Sık Kullanılan Kategori',
                'verbose_name_plural': 'Ana Sayfa Sık Kullanılan Kategoriler',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='homefeaturedproduct',
            constraint=models.UniqueConstraint(fields=('product',), name='unique_home_featured_product'),
        ),
        migrations.AddConstraint(
            model_name='homefeaturedcategory',
            constraint=models.UniqueConstraint(fields=('category',), name='unique_home_featured_category'),
        ),
    ]
