# Generated by Django 4.2.30 on 2026-06-27 10:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_herocampaign_homefeaturedproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='İstasyon Adı')),
                ('city', models.CharField(max_length=80, verbose_name='Şehir')),
                ('code', models.CharField(max_length=24, verbose_name='İstasyon Kodu')),
                ('address', models.CharField(blank=True, max_length=260, verbose_name='Adres')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kargo İstasyonu',
                'verbose_name_plural': 'Kargo İstasyonları',
                'ordering': ['display_order', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Takip Numarası')),
                ('status', models.CharField(choices=[('created', 'Kargo Kaydı Oluşturuldu'), ('picked_up', 'Satıcıdan Alındı'), ('in_transit', 'Transfer Sürecinde'), ('at_station', 'İstasyonda'), ('out_for_delivery', 'Dağıtıma Çıktı'), ('delivered', 'Teslim Edildi'), ('exception', 'Sorun Bildirildi'), ('returned', 'İade Sürecinde')], default='created', max_length=24, verbose_name='Kargo Durumu')),
                ('estimated_delivery', models.DateField(blank=True, null=True, verbose_name='Tahmini Teslimat')),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='Kargo Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kargo Takip Kaydı',
                'verbose_name_plural': 'Kargo Takip Kayıtları',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Kargo Firması')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Firma Kodu')),
                ('support_phone', models.CharField(blank=True, max_length=20, verbose_name='Destek Telefonu')),
                ('tracking_url', models.URLField(blank=True, verbose_name='Takip URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kargo Firması',
                'verbose_name_plural': 'Kargo Firmaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Kargo Kaydı Oluşturuldu'), ('picked_up', 'Satıcıdan Alındı'), ('in_transit', 'Transfer Sürecinde'), ('at_station', 'İstasyonda'), ('out_for_delivery', 'Dağıtıma Çıktı'), ('delivered', 'Teslim Edildi'), ('exception', 'Sorun Bildirildi'), ('returned', 'İade Sürecinde')], max_length=24, verbose_name='Durum')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Açıklama')),
                ('happened_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='İşlem Zamanı')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='store.shipment', verbose_name='Kargo Takip Kaydı')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.cargostation', verbose_name='İstasyon')),
            ],
            options={
                'verbose_name': 'Kargo Hareketi',
                'verbose_name_plural': 'Kargo Hareketleri',
                'ordering': ['-happened_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='store.shippingcompany', verbose_name='Kargo Firması'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_shipments', to='store.cargostation', verbose_name='Mevcut İstasyon'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='store.order', verbose_name='Sipariş'),
        ),
        migrations.AddField(
            model_name='cargostation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='store.shippingcompany', verbose_name='Kargo Firması'),
        ),
        migrations.AddConstraint(
            model_name='cargostation',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_station_code'),
        ),
    ]
