# Generated by Django 4.2.30 on 2026-06-27 10:53

from django.db import migrations


def create_corejet_stations(apps, schema_editor):
    ShippingCompany = apps.get_model('store', 'ShippingCompany')
    CargoStation = apps.get_model('store', 'CargoStation')

    corejet, _ = ShippingCompany.objects.get_or_create(
        code='CJ',
        defaults={
            'name': 'CoreJet',
            'support_phone': '0850 255 00 00',
            'tracking_url': '',
            'is_active': True,
        },
    )

    stations = [
        ('CJ-IST-HUB', 'İstanbul Ana Aktarma Merkezi', 'İstanbul', 'CoreJet İstanbul ana transfer ve çıkış merkezi', 10),
        ('CJ-ANK-HUB', 'Ankara İç Anadolu Transfer Merkezi', 'Ankara', 'İç Anadolu sipariş transfer istasyonu', 20),
        ('CJ-IZM-HUB', 'İzmir Ege Transfer Merkezi', 'İzmir', 'Ege bölgesi transfer istasyonu', 30),
        ('CJ-BRS-DIST', 'Bursa Marmara Dağıtım İstasyonu', 'Bursa', 'Marmara bölgesi dağıtım istasyonu', 40),
        ('CJ-ANT-DIST', 'Antalya Akdeniz Dağıtım İstasyonu', 'Antalya', 'Akdeniz bölgesi dağıtım istasyonu', 50),
        ('CJ-ADN-HUB', 'Adana Güney Transfer Merkezi', 'Adana', 'Güney ve çevre iller transfer istasyonu', 60),
        ('CJ-TRB-DIST', 'Trabzon Karadeniz Dağıtım İstasyonu', 'Trabzon', 'Karadeniz bölgesi dağıtım istasyonu', 70),
    ]

    for code, name, city, address, display_order in stations:
        CargoStation.objects.get_or_create(
            company=corejet,
            code=code,
            defaults={
                'name': name,
                'city': city,
                'address': address,
                'display_order': display_order,
                'is_active': True,
            },
        )


def remove_corejet_stations(apps, schema_editor):
    ShippingCompany = apps.get_model('store', 'ShippingCompany')
    CargoStation = apps.get_model('store', 'CargoStation')

    corejet = ShippingCompany.objects.filter(code='CJ').first()
    if corejet:
        CargoStation.objects.filter(company=corejet).delete()
        if not corejet.shipments.exists():
            corejet.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cargostation_shipment_shippingcompany_shipmentevent_and_more'),
    ]

    operations = [
        migrations.RunPython(create_corejet_stations, remove_corejet_stations),
    ]
