# Generated by Django 4.2.30 on 2026-06-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_seed_corejet_stations'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name='Fatura Adresi'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_company_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Firma Ünvanı'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Fatura E-postası'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_full_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Fatura Ad Soyad'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Fatura Telefonu'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_tax_number',
            field=models.CharField(blank=True, max_length=40, verbose_name='Vergi/TCKN No'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_tax_office',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vergi Dairesi'),
        ),
        migrations.AddField(
            model_name='order',
            name='billing_type',
            field=models.CharField(choices=[('individual', 'Bireysel'), ('corporate', 'Kurumsal')], default='individual', max_length=20, verbose_name='Fatura Tipi'),
        ),
        migrations.AddField(
            model_name='order',
            name='public_token',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True, verbose_name='Bilgilendirme Token'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=80, verbose_name='Teslimat Şehri'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, max_length=80, verbose_name='Teslimat İlçesi'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=12, verbose_name='Posta Kodu'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_recipient_name',
            field=models.CharField(blank=True, max_length=160, verbose_name='Alıcı Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.CreateModel(
            name='SiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('topic', models.CharField(choices=[('general', 'Genel'), ('order', 'Sipariş'), ('product', 'Ürün'), ('technical', 'Teknik')], default='general', max_length=24, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Çözüldü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Geri Bildirim',
                'verbose_name_plural': 'Geri Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Puan')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Başlık')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Yayında')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Ürün Yorumu',
                'verbose_name_plural': 'Ürün Yorumları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPhoneNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('tracking_link', models.URLField(max_length=500, verbose_name='Bilgilendirme Linki')),
                ('status', models.CharField(choices=[('pending', 'Gönderim Bekliyor'), ('sent', 'Gönderildi'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('provider_response', models.TextField(blank=True, verbose_name='Sağlayıcı Yanıtı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_notifications', to='store.order', verbose_name='Sipariş')),
            ],
            options={
                'verbose_name': 'Telefon Bilgilendirme Kaydı',
                'verbose_name_plural': 'Telefon Bilgilendirme Kayıtları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Adresim', max_length=80, verbose_name='Adres Başlığı')),
                ('recipient_name', models.CharField(max_length=160, verbose_name='Alıcı Ad Soyad')),
                ('phone', models.CharField(max_length=20, verbose_name='Kargo Telefonu')),
                ('city', models.CharField(max_length=80, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='İlçe')),
                ('address_line', models.TextField(verbose_name='Açık Adres')),
                ('postal_code', models.CharField(blank=True, max_length=12, verbose_name='Posta Kodu')),
                ('is_default', models.BooleanField(default=False, verbose_name='Varsayılan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kayıtlı Adres',
                'verbose_name_plural': 'Kayıtlı Adresler',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.customeraddress', verbose_name='Kayıtlı Adres'),
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='unique_product_review_per_user'),
        ),
    ]
