# Generated by Django 4.2.30 on 2026-06-27 16:29

from django.db import migrations, models
import django.db.models.deletion


def create_default_card_groups(apps, schema_editor):
    CardInstallmentGroup = apps.get_model('store', 'CardInstallmentGroup')
    defaults = [
        {
            'name': 'Anlaşmalı Kartlar',
            'slug': 'anlasmali-kartlar',
            'description': 'Admin panelinden banka/kart ailesi olarak düzenlenebilir.',
            'default_max_installments': 6,
            'display_order': 10,
        },
        {
            'name': 'Diğer Kartlar',
            'slug': 'diger-kartlar',
            'description': 'Özel kural bulunmayan kartlar için varsayılan grup.',
            'default_max_installments': 3,
            'display_order': 20,
        },
    ]
    for item in defaults:
        CardInstallmentGroup.objects.get_or_create(slug=item['slug'], defaults=item)


def remove_default_card_groups(apps, schema_editor):
    CardInstallmentGroup = apps.get_model('store', 'CardInstallmentGroup')
    CardInstallmentGroup.objects.filter(slug__in=['anlasmali-kartlar', 'diger-kartlar']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_billing_address_order_billing_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInstallmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Kart Grubu Adı')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Kod')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Açıklama')),
                ('default_max_installments', models.PositiveSmallIntegerField(default=1, verbose_name='Varsayılan En Fazla Taksit')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kart Taksit Grubu',
                'verbose_name_plural': 'Kart Taksit Grupları',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryInstallmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_installments', models.PositiveSmallIntegerField(default=1, verbose_name='En Fazla Taksit')),
                ('min_cart_amount', models.DecimalField(decimal_places=2, default=0, help_text='Bu tutarın altındaki sepetlerde kural uygulanmaz.', max_digits=10, verbose_name='Minimum Sepet Tutarı')),
                ('priority', models.PositiveSmallIntegerField(default=0, verbose_name='Öncelik')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='store.cardinstallmentgroup', verbose_name='Kart Grubu')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_rules', to='store.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kategori Taksit Kuralı',
                'verbose_name_plural': 'Kategori Taksit Kuralları',
                'ordering': ['category__name', 'card_group__display_order', '-priority'],
            },
        ),
        migrations.RunPython(create_default_card_groups, remove_default_card_groups),
        migrations.AddField(
            model_name='order',
            name='installment_base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taksit Öncesi Tutar'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_card_group_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Kart Grubu Adı'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Taksit Sayısı'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_monthly_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Tutar'),
        ),
        migrations.AddField(
            model_name='order',
            name='installment_rate_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Vade Farkı (%)'),
        ),
        migrations.CreateModel(
            name='InstallmentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_count', models.PositiveSmallIntegerField(verbose_name='Taksit Sayısı')),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, default=0, help_text='Örn: 7.50 yazılırsa toplam tutara yüzde 7,5 eklenir.', max_digits=5, verbose_name='Vade Farkı (%)')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='store.categoryinstallmentrule', verbose_name='Taksit Kuralı')),
            ],
            options={
                'verbose_name': 'Taksit Vade Oranı',
                'verbose_name_plural': 'Taksit Vade Oranları',
                'ordering': ['installment_count'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='installment_card_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store.cardinstallmentgroup', verbose_name='Taksit Kart Grubu'),
        ),
        migrations.AddConstraint(
            model_name='installmentrate',
            constraint=models.UniqueConstraint(fields=('rule', 'installment_count'), name='unique_installment_rate_per_rule'),
        ),
    ]
