# Generated by Django 4.2.30 on 2026-06-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_fix_missing_seed_media_references'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardBinPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=120, verbose_name='Banka/Kart Adı')),
                ('prefix', models.CharField(help_text='Kart numarasının ilk 6, 7 veya 8 hanesi. Örn: 454360 veya 45436012', max_length=8, unique=True, verbose_name='Kart İlk 6-8 Hane')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_prefixes', to='store.cardinstallmentgroup', verbose_name='Taksit Grubu')),
            ],
            options={
                'verbose_name': 'Kart BIN Tanımı',
                'verbose_name_plural': 'Kart BIN Tanımları',
                'ordering': ['bank_name', '-prefix'],
            },
        ),
    ]
