# Generated by Django 4.2.30 on 2026-06-27 16:59

from django.db import migrations, models


def mark_unknown_card_default(apps, schema_editor):
    CardInstallmentGroup = apps.get_model('store', 'CardInstallmentGroup')
    fallback = CardInstallmentGroup.objects.filter(slug='diger-kartlar').first()
    if fallback is None:
        fallback = CardInstallmentGroup.objects.order_by('-display_order', 'name').first()
    if fallback is not None:
        CardInstallmentGroup.objects.update(is_default_for_unknown_cards=False)
        fallback.is_default_for_unknown_cards = True
        fallback.save(update_fields=['is_default_for_unknown_cards'])


def clear_unknown_card_default(apps, schema_editor):
    CardInstallmentGroup = apps.get_model('store', 'CardInstallmentGroup')
    CardInstallmentGroup.objects.update(is_default_for_unknown_cards=False)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cardbinprefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinstallmentgroup',
            name='is_default_for_unknown_cards',
            field=models.BooleanField(default=False, verbose_name='Tanımsız Kartlar İçin Varsayılan'),
        ),
        migrations.RunPython(mark_unknown_card_default, clear_unknown_card_default),
    ]
