# Generated by Django 4.2.30 on 2026-06-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cardinstallmentgroup_is_default_for_unknown_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Fotoğraf'), ('video', 'Video')], default='image', max_length=12, verbose_name='Medya Tipi')),
                ('file', models.FileField(upload_to='product_media/', verbose_name='Dosya')),
                ('title', models.CharField(blank=True, max_length=140, verbose_name='Başlık')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='store.product', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Ürün Medyası',
                'verbose_name_plural': 'Ürün Medyaları',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
