# Generated by Codex on 2026-06-30

from django.db import migrations


COREJET_STATIONS = [
    ('CJ-TR-01', 'Adana Seyhan Dağıtım İstasyonu', 'Adana', 'Seyhan ve çevre ilçeler CoreJet dağıtım noktası'),
    ('CJ-TR-02', 'Adıyaman Merkez Dağıtım İstasyonu', 'Adıyaman', 'Adıyaman merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-03', 'Afyonkarahisar Merkez Transfer Noktası', 'Afyonkarahisar', 'İç Ege bağlantılı CoreJet transfer noktası'),
    ('CJ-TR-04', 'Ağrı Merkez Dağıtım İstasyonu', 'Ağrı', 'Ağrı ve Doğu Anadolu kırsal dağıtım noktası'),
    ('CJ-TR-05', 'Amasya Merkez Dağıtım İstasyonu', 'Amasya', 'Amasya merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-06', 'Ankara Yenimahalle Transfer Merkezi', 'Ankara', 'Başkent içi ve İç Anadolu dağıtım transfer noktası'),
    ('CJ-TR-07', 'Antalya Muratpaşa Dağıtım İstasyonu', 'Antalya', 'Antalya merkez ve turizm bölgesi dağıtım noktası'),
    ('CJ-TR-08', 'Artvin Merkez Dağıtım İstasyonu', 'Artvin', 'Artvin ve Doğu Karadeniz sahil bağlantı noktası'),
    ('CJ-TR-09', 'Aydın Efeler Dağıtım İstasyonu', 'Aydın', 'Aydın Efeler ve kıyı ilçeleri dağıtım noktası'),
    ('CJ-TR-10', 'Balıkesir Karesi Transfer Noktası', 'Balıkesir', 'Kuzey Ege ve Marmara bağlantılı transfer noktası'),
    ('CJ-TR-11', 'Bilecik Merkez Dağıtım İstasyonu', 'Bilecik', 'Bilecik ve çevre sanayi bölgeleri dağıtım noktası'),
    ('CJ-TR-12', 'Bingöl Merkez Dağıtım İstasyonu', 'Bingöl', 'Bingöl merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-13', 'Bitlis Tatvan Dağıtım İstasyonu', 'Bitlis', 'Bitlis, Tatvan ve Van Gölü çevresi dağıtım noktası'),
    ('CJ-TR-14', 'Bolu Merkez Transfer Noktası', 'Bolu', 'Batı Karadeniz ve TEM hattı transfer noktası'),
    ('CJ-TR-15', 'Burdur Merkez Dağıtım İstasyonu', 'Burdur', 'Burdur ve Göller Yöresi dağıtım noktası'),
    ('CJ-TR-16', 'Bursa Nilüfer Dağıtım İstasyonu', 'Bursa', 'Bursa şehir içi ve sanayi bölgeleri dağıtım noktası'),
    ('CJ-TR-17', 'Çanakkale Merkez Dağıtım İstasyonu', 'Çanakkale', 'Çanakkale merkez ve boğaz hattı dağıtım noktası'),
    ('CJ-TR-18', 'Çankırı Merkez Dağıtım İstasyonu', 'Çankırı', 'Çankırı merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-19', 'Çorum Merkez Transfer Noktası', 'Çorum', 'Orta Karadeniz ve İç Anadolu geçiş noktası'),
    ('CJ-TR-20', 'Denizli Merkez Dağıtım İstasyonu', 'Denizli', 'Denizli merkez ve tekstil bölgesi dağıtım noktası'),
    ('CJ-TR-21', 'Diyarbakır Kayapınar Transfer Merkezi', 'Diyarbakır', 'Güneydoğu Anadolu bölgesel transfer noktası'),
    ('CJ-TR-22', 'Edirne Merkez Dağıtım İstasyonu', 'Edirne', 'Trakya batı hattı CoreJet dağıtım noktası'),
    ('CJ-TR-23', 'Elazığ Merkez Transfer Noktası', 'Elazığ', 'Doğu Anadolu bağlantılı transfer noktası'),
    ('CJ-TR-24', 'Erzincan Merkez Dağıtım İstasyonu', 'Erzincan', 'Erzincan merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-25', 'Erzurum Yakutiye Transfer Merkezi', 'Erzurum', 'Kuzeydoğu Anadolu bölgesel transfer noktası'),
    ('CJ-TR-26', 'Eskişehir Odunpazarı Dağıtım İstasyonu', 'Eskişehir', 'Eskişehir şehir içi ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-27', 'Gaziantep Şahinbey Transfer Merkezi', 'Gaziantep', 'Güneydoğu e-ticaret ve sanayi transfer noktası'),
    ('CJ-TR-28', 'Giresun Merkez Dağıtım İstasyonu', 'Giresun', 'Giresun ve Orta Karadeniz sahil dağıtım noktası'),
    ('CJ-TR-29', 'Gümüşhane Merkez Dağıtım İstasyonu', 'Gümüşhane', 'Gümüşhane ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-30', 'Hakkari Merkez Dağıtım İstasyonu', 'Hakkari', 'Hakkari merkez ve sınır hattı dağıtım noktası'),
    ('CJ-TR-31', 'Hatay Antakya Dağıtım İstasyonu', 'Hatay', 'Hatay merkez ve Akdeniz kıyı ilçeleri dağıtım noktası'),
    ('CJ-TR-32', 'Isparta Merkez Dağıtım İstasyonu', 'Isparta', 'Isparta ve Göller Yöresi dağıtım noktası'),
    ('CJ-TR-33', 'Mersin Akdeniz Transfer Merkezi', 'Mersin', 'Liman hattı ve Akdeniz bölgesel transfer noktası'),
    ('CJ-TR-34', 'İstanbul Kağıthane Dağıtım İstasyonu', 'İstanbul', 'İstanbul merkez Avrupa yakası dağıtım noktası'),
    ('CJ-TR-35', 'İzmir Bornova Dağıtım İstasyonu', 'İzmir', 'İzmir şehir içi ve Ege lojistik bağlantı noktası'),
    ('CJ-TR-36', 'Kars Merkez Dağıtım İstasyonu', 'Kars', 'Kars ve Kuzeydoğu Anadolu dağıtım noktası'),
    ('CJ-TR-37', 'Kastamonu Merkez Dağıtım İstasyonu', 'Kastamonu', 'Kastamonu ve Batı Karadeniz iç hat dağıtım noktası'),
    ('CJ-TR-38', 'Kayseri Melikgazi Transfer Merkezi', 'Kayseri', 'Orta Anadolu bölgesel transfer noktası'),
    ('CJ-TR-39', 'Kırklareli Merkez Dağıtım İstasyonu', 'Kırklareli', 'Trakya kuzey hattı CoreJet dağıtım noktası'),
    ('CJ-TR-40', 'Kırşehir Merkez Dağıtım İstasyonu', 'Kırşehir', 'Kırşehir merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-41', 'Kocaeli İzmit Transfer Merkezi', 'Kocaeli', 'Marmara sanayi ve liman hattı transfer noktası'),
    ('CJ-TR-42', 'Konya Karatay Transfer Merkezi', 'Konya', 'İç Anadolu güney hattı bölgesel transfer noktası'),
    ('CJ-TR-43', 'Kütahya Merkez Dağıtım İstasyonu', 'Kütahya', 'Kütahya ve İç Ege dağıtım noktası'),
    ('CJ-TR-44', 'Malatya Yeşilyurt Transfer Noktası', 'Malatya', 'Doğu Anadolu batı bağlantı transfer noktası'),
    ('CJ-TR-45', 'Manisa Yunusemre Dağıtım İstasyonu', 'Manisa', 'Manisa sanayi ve şehir içi dağıtım noktası'),
    ('CJ-TR-46', 'Kahramanmaraş Onikişubat Dağıtım İstasyonu', 'Kahramanmaraş', 'Kahramanmaraş merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-47', 'Mardin Artuklu Dağıtım İstasyonu', 'Mardin', 'Mardin ve Mezopotamya hattı dağıtım noktası'),
    ('CJ-TR-48', 'Muğla Menteşe Dağıtım İstasyonu', 'Muğla', 'Muğla merkez ve kıyı ilçeleri dağıtım noktası'),
    ('CJ-TR-49', 'Muş Merkez Dağıtım İstasyonu', 'Muş', 'Muş merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-50', 'Nevşehir Merkez Dağıtım İstasyonu', 'Nevşehir', 'Kapadokya bölgesi CoreJet dağıtım noktası'),
    ('CJ-TR-51', 'Niğde Merkez Dağıtım İstasyonu', 'Niğde', 'Niğde merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-52', 'Ordu Altınordu Dağıtım İstasyonu', 'Ordu', 'Ordu ve Orta Karadeniz sahil dağıtım noktası'),
    ('CJ-TR-53', 'Rize Merkez Dağıtım İstasyonu', 'Rize', 'Rize ve Doğu Karadeniz sahil dağıtım noktası'),
    ('CJ-TR-54', 'Sakarya Adapazarı Transfer Noktası', 'Sakarya', 'Marmara doğu hattı CoreJet transfer noktası'),
    ('CJ-TR-55', 'Samsun İlkadım Transfer Merkezi', 'Samsun', 'Karadeniz bölgesel transfer noktası'),
    ('CJ-TR-56', 'Siirt Merkez Dağıtım İstasyonu', 'Siirt', 'Siirt merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-57', 'Sinop Merkez Dağıtım İstasyonu', 'Sinop', 'Sinop ve Karadeniz kuzey hattı dağıtım noktası'),
    ('CJ-TR-58', 'Sivas Merkez Transfer Noktası', 'Sivas', 'İç Anadolu doğu hattı transfer noktası'),
    ('CJ-TR-59', 'Tekirdağ Çorlu Transfer Merkezi', 'Tekirdağ', 'Trakya sanayi ve liman hattı transfer noktası'),
    ('CJ-TR-60', 'Tokat Merkez Dağıtım İstasyonu', 'Tokat', 'Tokat merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-61', 'Trabzon Ortahisar Transfer Merkezi', 'Trabzon', 'Doğu Karadeniz bölgesel transfer noktası'),
    ('CJ-TR-62', 'Tunceli Merkez Dağıtım İstasyonu', 'Tunceli', 'Tunceli merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-63', 'Şanlıurfa Haliliye Transfer Noktası', 'Şanlıurfa', 'Güneydoğu ova hattı CoreJet transfer noktası'),
    ('CJ-TR-64', 'Uşak Merkez Dağıtım İstasyonu', 'Uşak', 'Uşak ve İç Ege dağıtım noktası'),
    ('CJ-TR-65', 'Van İpekyolu Transfer Merkezi', 'Van', 'Van Gölü ve Doğu Anadolu bölgesel transfer noktası'),
    ('CJ-TR-66', 'Yozgat Merkez Dağıtım İstasyonu', 'Yozgat', 'Yozgat merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-67', 'Zonguldak Merkez Dağıtım İstasyonu', 'Zonguldak', 'Batı Karadeniz kıyı hattı dağıtım noktası'),
    ('CJ-TR-68', 'Aksaray Merkez Dağıtım İstasyonu', 'Aksaray', 'Aksaray ve Kapadokya bağlantı dağıtım noktası'),
    ('CJ-TR-69', 'Bayburt Merkez Dağıtım İstasyonu', 'Bayburt', 'Bayburt merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-70', 'Karaman Merkez Dağıtım İstasyonu', 'Karaman', 'Karaman merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-71', 'Kırıkkale Merkez Transfer Noktası', 'Kırıkkale', 'Ankara çevre lojistik bağlantı noktası'),
    ('CJ-TR-72', 'Batman Merkez Dağıtım İstasyonu', 'Batman', 'Batman merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-73', 'Şırnak Merkez Dağıtım İstasyonu', 'Şırnak', 'Şırnak ve sınır hattı dağıtım noktası'),
    ('CJ-TR-74', 'Bartın Merkez Dağıtım İstasyonu', 'Bartın', 'Bartın ve Batı Karadeniz kıyı dağıtım noktası'),
    ('CJ-TR-75', 'Ardahan Merkez Dağıtım İstasyonu', 'Ardahan', 'Ardahan ve Kuzeydoğu Anadolu dağıtım noktası'),
    ('CJ-TR-76', 'Iğdır Merkez Dağıtım İstasyonu', 'Iğdır', 'Iğdır ve sınır hattı dağıtım noktası'),
    ('CJ-TR-77', 'Yalova Merkez Dağıtım İstasyonu', 'Yalova', 'Yalova ve Marmara kıyı dağıtım noktası'),
    ('CJ-TR-78', 'Karabük Merkez Dağıtım İstasyonu', 'Karabük', 'Karabük ve sanayi hattı dağıtım noktası'),
    ('CJ-TR-79', 'Kilis Merkez Dağıtım İstasyonu', 'Kilis', 'Kilis merkez ve çevre ilçeler dağıtım noktası'),
    ('CJ-TR-80', 'Osmaniye Merkez Dağıtım İstasyonu', 'Osmaniye', 'Osmaniye ve Çukurova doğu hattı dağıtım noktası'),
    ('CJ-TR-81', 'Düzce Merkez Transfer Noktası', 'Düzce', 'TEM hattı Marmara ve Karadeniz bağlantı noktası'),
    ('CJ-MT-01', 'İstanbul Avrupa Aktarma Merkezi', 'İstanbul', 'Avrupa yakası yüksek hacimli e-ticaret aktarma merkezi'),
    ('CJ-MT-02', 'İstanbul Anadolu Aktarma Merkezi', 'İstanbul', 'Anadolu yakası yüksek hacimli e-ticaret aktarma merkezi'),
    ('CJ-MT-03', 'İstanbul Esenyurt Mikro Dağıtım', 'İstanbul', 'Esenyurt, Beylikdüzü ve Avcılar mikro dağıtım noktası'),
    ('CJ-MT-04', 'İstanbul Tuzla Lojistik Noktası', 'İstanbul', 'Tuzla, Pendik ve Gebze bağlantılı lojistik noktası'),
    ('CJ-MT-05', 'Ankara Sincan Mikro Dağıtım', 'Ankara', 'Sincan, Etimesgut ve OSB hattı mikro dağıtım noktası'),
    ('CJ-MT-06', 'Ankara Çankaya Dağıtım İstasyonu', 'Ankara', 'Çankaya ve merkezi iş alanları dağıtım noktası'),
    ('CJ-MT-07', 'İzmir Kemalpaşa Lojistik Merkezi', 'İzmir', 'Kemalpaşa sanayi ve Ege iç hat lojistik noktası'),
    ('CJ-MT-08', 'Bursa Osmangazi Mikro Dağıtım', 'Bursa', 'Osmangazi, Yıldırım ve merkez ilçeler mikro dağıtım noktası'),
    ('CJ-MT-09', 'Antalya Kepez Mikro Dağıtım', 'Antalya', 'Kepez, Aksu ve kuzey Antalya dağıtım noktası'),
    ('CJ-MT-10', 'Kocaeli Gebze Lojistik Merkezi', 'Kocaeli', 'Gebze, Dilovası ve sanayi hattı lojistik noktası'),
    ('CJ-MT-11', 'Konya Selçuklu Mikro Dağıtım', 'Konya', 'Selçuklu ve şehir içi yüksek hacimli dağıtım noktası'),
    ('CJ-MT-12', 'Gaziantep Şehitkamil Lojistik Merkezi', 'Gaziantep', 'Şehitkamil sanayi ve Güneydoğu bağlantı noktası'),
]


def seed_corejet_station_network(apps, schema_editor):
    ShippingCompany = apps.get_model('store', 'ShippingCompany')
    CargoStation = apps.get_model('store', 'CargoStation')

    corejet, _ = ShippingCompany.objects.get_or_create(
        code='CJ',
        defaults={
            'name': 'CoreJet',
            'support_phone': '0850 255 00 00',
            'tracking_url': '',
            'is_active': True,
        },
    )

    for index, (code, name, city, address) in enumerate(COREJET_STATIONS, start=1):
        CargoStation.objects.update_or_create(
            company=corejet,
            code=code,
            defaults={
                'name': name,
                'city': city,
                'address': address,
                'display_order': 100 + index,
                'is_active': True,
            },
        )


def remove_corejet_station_network(apps, schema_editor):
    ShippingCompany = apps.get_model('store', 'ShippingCompany')
    CargoStation = apps.get_model('store', 'CargoStation')

    corejet = ShippingCompany.objects.filter(code='CJ').first()
    if corejet:
        CargoStation.objects.filter(
            company=corejet,
            code__in=[station[0] for station in COREJET_STATIONS],
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productmedia'),
    ]

    operations = [
        migrations.RunPython(seed_corejet_station_network, remove_corejet_station_network),
    ]
