# Generated by Django 4.2.30 on 2026-06-30 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0013_seed_corejet_station_network'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cancel', 'İptal Talebi'), ('return', 'İade Talebi')], max_length=12, verbose_name='Talep Tipi')),
                ('reason', models.CharField(max_length=160, verbose_name='Sebep')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('completed', 'Tamamlandı')], default='pending', max_length=16, verbose_name='Durum')),
                ('admin_note', models.TextField(blank=True, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='store.order', verbose_name='Sipariş')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_service_requests', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'İade/İptal Talebi',
                'verbose_name_plural': 'İade/İptal Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='store.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Favori Ürün',
                'verbose_name_plural': 'Favori Ürünler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompareProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_by', to='store.product', verbose_name='Ürün')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_products', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Karşılaştırma Ürünü',
                'verbose_name_plural': 'Karşılaştırma Ürünleri',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='orderservicerequest',
            constraint=models.UniqueConstraint(fields=('order', 'request_type'), name='unique_order_service_request_type'),
        ),
        migrations.AddConstraint(
            model_name='favoriteproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite_product_per_user'),
        ),
        migrations.AddConstraint(
            model_name='compareproduct',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_compare_product_per_user'),
        ),
    ]
