# Generated by Django 4.2.30 on 2026-07-01 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0015_productquestion_productvariant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('general', 'Genel Destek'), ('return', 'İade'), ('cancel', 'İptal'), ('shipping', 'Kargo'), ('billing', 'Fatura/Ödeme'), ('damaged', 'Hasarlı Ürün')], default='general', max_length=20, verbose_name='Talep Tipi')),
                ('subject', models.CharField(max_length=180, verbose_name='Konu')),
                ('status', models.CharField(choices=[('open', 'Açık'), ('waiting_customer', 'Müşteri Yanıtı Bekleniyor'), ('waiting_support', 'Destek Yanıtı Bekleniyor'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='open', max_length=24, verbose_name='Durum')),
                ('ai_summary', models.TextField(blank=True, verbose_name='AI Özet')),
                ('ai_suggestion', models.TextField(blank=True, verbose_name='AI Önerisi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Zamanı')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='store.order', verbose_name='Sipariş')),
                ('service_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_ticket', to='store.orderservicerequest', verbose_name='İade/İptal Talebi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Müşteri')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('customer', 'Müşteri'), ('support', 'Destek'), ('vendor', 'Satıcı'), ('ai', 'AI Destek'), ('system', 'Sistem')], max_length=16, verbose_name='Gönderen Tipi')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_internal', models.BooleanField(default=False, verbose_name='İç Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='store.supportticket', verbose_name='Destek Talebi')),
            ],
            options={
                'verbose_name': 'Destek Mesajı',
                'verbose_name_plural': 'Destek Mesajları',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', 'Sipariş'), ('shipping', 'Kargo'), ('support', 'Destek'), ('question', 'Soru-Cevap'), ('review', 'Yorum'), ('system', 'Sistem')], default='system', max_length=20, verbose_name='Bildirim Tipi')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('link_url', models.CharField(blank=True, max_length=320, verbose_name='Bağlantı')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Okunma Zamanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Zamanı')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='İşlemi Yapan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at', '-created_at'], name='store_notif_recipie_fa1133_idx')],
            },
        ),
    ]
