# Generated by Django 4.2.30 on 2026-06-27 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_2fa_enabled',
            field=models.BooleanField(default=True, verbose_name='E-posta 2FA aktif'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='E-posta doğrulama zamanı'),
        ),
        migrations.CreateModel(
            name='EmailTwoFactorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Giriş doğrulama'), ('register', 'Kayıt doğrulama')], max_length=20, verbose_name='Amaç')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Kod özeti')),
                ('sent_to', models.EmailField(max_length=254, verbose_name='Gönderilen e-posta')),
                ('expires_at', models.DateTimeField(verbose_name='Son geçerlilik')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Kullanım zamanı')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Deneme sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma zamanı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_2fa_codes', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'E-posta 2FA Kodu',
                'verbose_name_plural': 'E-posta 2FA Kodları',
                'ordering': ['-created_at'],
            },
        ),
    ]
