# Generated by Django 4.2.30 on 2026-06-21 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Şirket Adı')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Vergi Numarası')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_applications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Satıcı Başvurusu',
                'verbose_name_plural': 'Satıcı Başvuruları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='Mağaza Adı')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vendors/logos/', verbose_name='Logo')),
                ('tax_number', models.CharField(max_length=20, unique=True, verbose_name='Vergi Numarası')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Onaylı')),
                ('product_limit', models.PositiveIntegerField(default=50, verbose_name='Ürün Limiti')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Satıcı',
                'verbose_name_plural': 'Satıcılar',
            },
        ),
    ]
