# Generated by Django 4.2.30 on 2026-07-01 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productquestion_productvariant_and_more'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Paket Adı')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('service_type', models.CharField(choices=[('setup', 'Mağaza Kurulum'), ('product_upload', 'Ürün Yükleme'), ('design', 'Görsel / Vitrin Tasarım'), ('consulting', 'Satış Danışmanlığı'), ('priority_support', 'Öncelikli Destek')], max_length=24, verbose_name='Hizmet Tipi')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('delivery_days', models.PositiveIntegerField(default=3, verbose_name='Teslim Süresi (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Hizmet ve Destek Paketi',
                'verbose_name_plural': 'Hizmet ve Destek Paketleri',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Paket Adı')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.CharField(blank=True, max_length=260, verbose_name='Açıklama')),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Ücret')),
                ('product_limit', models.PositiveIntegerField(default=20, verbose_name='Ürün Limiti')),
                ('sponsored_product_quota', models.PositiveIntegerField(default=0, verbose_name='Sponsorlu Ürün Hakkı')),
                ('ad_credit', models.PositiveIntegerField(default=0, verbose_name='Reklam Kredisi')),
                ('support_level', models.CharField(default='Standart destek', max_length=120, verbose_name='Destek Seviyesi')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Satıcı Abonelik Paketi',
                'verbose_name_plural': 'Satıcı Abonelik Paketleri',
                'ordering': ['display_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='VendorSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ödeme/Onay Bekliyor'), ('active', 'Aktif'), ('expired', 'Süresi Doldu'), ('cancelled', 'İptal')], default='pending', max_length=16, verbose_name='Durum')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='Otomatik Yenile')),
                ('payment_note', models.CharField(blank=True, max_length=240, verbose_name='Ödeme Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='vendors.vendorsubscriptionplan', verbose_name='Paket')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='vendors.vendor', verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Satıcı Aboneliği',
                'verbose_name_plural': 'Satıcı Abonelikleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_note', models.TextField(blank=True, verbose_name='Talep Notu')),
                ('status', models.CharField(choices=[('pending', 'Talep Alındı'), ('in_progress', 'İşlemde'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal')], default='pending', max_length=16, verbose_name='Durum')),
                ('admin_note', models.TextField(blank=True, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='vendors.supportservicepackage', verbose_name='Paket')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to='vendors.vendor', verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Hizmet ve Destek Talebi',
                'verbose_name_plural': 'Hizmet ve Destek Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SponsoredProductCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home', 'Ana Sayfa'), ('category', 'Kategori Sayfası'), ('search', 'Arama Sonuçları')], default='home', max_length=16, verbose_name='Yerleşim')),
                ('title', models.CharField(blank=True, max_length=160, verbose_name='Kampanya Başlığı')),
                ('daily_budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Günlük Bütçe')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('pending', 'Onay Bekliyor'), ('active', 'Yayında'), ('paused', 'Duraklatıldı'), ('rejected', 'Reddedildi'), ('ended', 'Bitti')], default='pending', max_length=16, verbose_name='Durum')),
                ('admin_note', models.CharField(blank=True, max_length=240, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to='store.product', verbose_name='Ürün')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsored_campaigns', to='vendors.vendor', verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Sponsorlu Ürün Kampanyası',
                'verbose_name_plural': 'Sponsorlu Ürün Kampanyaları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=220, verbose_name='Resmi Ünvan')),
                ('trade_name', models.CharField(blank=True, max_length=220, verbose_name='Ticari Ünvan / Marka')),
                ('tax_office', models.CharField(max_length=120, verbose_name='Vergi Dairesi')),
                ('tax_number', models.CharField(max_length=20, verbose_name='Vergi / TCKN No')),
                ('mersis_no', models.CharField(blank=True, max_length=32, verbose_name='MERSİS No')),
                ('contact_person', models.CharField(max_length=160, verbose_name='Yetkili Kişi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='Fatura E-postası')),
                ('city', models.CharField(max_length=80, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=80, verbose_name='İlçe')),
                ('address', models.TextField(verbose_name='İşletme Adresi')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('website', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Yönetici Onaylı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to='vendors.vendor', verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'İşletme Profili',
                'verbose_name_plural': 'İşletme Profilleri',
            },
        ),
        migrations.CreateModel(
            name='AdPlacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('home_board', 'Ana Sayfa Reklam Panosu'), ('category_top', 'Kategori Üst Banner'), ('search_top', 'Arama Üst Banner')], max_length=20, verbose_name='Reklam Alanı')),
                ('title', models.CharField(max_length=160, verbose_name='Başlık')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Kısa Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vendor_ads/', verbose_name='Görsel')),
                ('target_url', models.CharField(blank=True, max_length=300, verbose_name='Hedef Link')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tutar')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Başlangıç')),
                ('ends_at', models.DateTimeField(verbose_name='Bitiş')),
                ('status', models.CharField(choices=[('pending', 'Onay Bekliyor'), ('active', 'Yayında'), ('rejected', 'Reddedildi'), ('ended', 'Bitti')], default='pending', max_length=16, verbose_name='Durum')),
                ('admin_note', models.CharField(blank=True, max_length=240, verbose_name='Yönetici Notu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_requests', to='vendors.vendor', verbose_name='Satıcı')),
            ],
            options={
                'verbose_name': 'Reklam Alanı Talebi',
                'verbose_name_plural': 'Reklam Alanı Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
